import type { Metadata } from "next";
import { Lexend_Deca, Nunito } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welp | Local Business Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${lexendDeca.variable} ${nunito.variable}`}>
        <Nav />
        <section className={"main"}>
          {children}
        </section>
      
        <div className={"verticalDivider"}></div>

        <footer>Copyright © Never-Ever Welp Inc. Welp, Welp logo and related marks are NOT registered trademarks of Welp.</footer>
      </body>
    </html>
  );
}